# Generated by Django 3.1.6 on 2021-02-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='library',
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(default='Free', max_length=100),
        ),
    ]
