# Generated by Django 3.1.6 on 2021-02-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210204_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='library',
            field=models.ManyToManyField(to='main_app.Movie'),
        ),
    ]
